In [1]:
a = [1, 2, 3]
print(a + [4, 5])

[1, 2, 3, 4, 5]


In [2]:
import numpy as np

b = np.array([1, 2, 3])
print(b + np.array([4, 5, 6]))

[5 7 9]


In [6]:
import numpy as np

arr1 = np.array([6, 7.5, 8, 0, 1])
print(type(arr1))


<class 'numpy.ndarray'>


In [7]:
arr2 = arr1 * 5
arr2

array([30. , 37.5, 40. ,  0. ,  5. ])

In [8]:
arr3 = arr1 / 10
arr3

array([0.6 , 0.75, 0.8 , 0.  , 0.1 ])

In [13]:
np.arange(5)
np.arange(2, 6)
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [15]:
import numpy as np
import math
import matplotlib.pyplot as plt

t = np.arange(0, 2.5, 0.1)
#print(len(t))
t1 = t * math.pi
y1 = np.sin(t1)
y2 = np.cos(t1)
print(len(y1))

fig = plt.figure()
axes = fig.add_subplot(1,1,1)
axes.plot(t, y1)
axes.plot(t, y2)
plt.show()

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/chenyichieh/Documents/GitHub/python_project/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
  File "/var/folders/p5/g_46v2nj4w54b_7zzd1ss6xh0000gn/T/ipykernel_61031/604532205.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenyichieh/Documents/GitHub/python_project/.venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 45, in get_style_by_name
ModuleNotFoundError: No module named 'pygments.styles.default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenyichieh/Documents/GitHub/python_project/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
  File "/Users/chenyichieh/Documents/G